apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mini-project
spec:
  replicas: 2 # Number of pods
  selector:
    matchLabels:
      app: k8s-mini-project
  template:
    metadata:
      labels:
        app: k8s-mini-project
    spec:
      containers:
        - name: k8s-mini-project
          image: k8s-mini-project:latest
          imagePullPolicy: Never # Tell Kubernetes not to pull from a registry
          # image: vikash95/kubernetes-test-app:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mini-project
spec:
  selector:
    app: k8s-mini-project
  ports:
    - port: 8080
      targetPort: 5000
